table_fields = ['URL',
'Gender',
'Name day',
'Word/name',
'Meaning',
'Related names',
'Pronunciation',
'Language(s)',
'Derivation',
'Region of origin',
'Country',
'State',
'Nickname(s)',
'Variant form(s)',
'Named for',
'Popularity',
'Derivative(s)',
'Notable rulers',
'Othernames',
'Also known as',
'Origin',
'Birth name',
'Norse name',
'Meaning of name',
'Ethnicity[4]',
'Ethnicity[1]',
'Ethnicity',
'Nativename',
'Earlier spellings',
'Place of origin',
'Abbreviations',
'Key people',
'Word/Name',
'Significant other(s)']
